### ISSUE TITLE
Amazon Brand Smart Thermostat Not Working Correctly

### ISSUE THREAD

**Issue by tateu** [joeyhage/homebridge-alexa-smarthome#147]
**Describe The Bug:**

My Thermostat (Amazon Brand Smart Thermostat) returns a supported operation of setTargetSetpoint instead of setTargetTemperature and would not load with an error of UnsupportedDeviceError.  So, I tried simply removing setTargetTemperature from requiredOperations in thermostat-accessory.ts. 

```static requiredOperations: SupportedActionsType[] = [];```

That worked to allow the Thermostat to load into HomeBridge.  I then went about trying to change the Temperature.  The first time was successful but most of the time I get error messages with "rate exceeded response."  I then left it alone for 30-40 minutes and was successful in changing the Temperature again but two minutes after the successful change, I started getting the rate limit error again.  I don't know what Amazon's "Set" rate limit is but it seems to be ridiculously high, 5 minutes, 10 minutes, etc.???

Authentication checks, "Get current temperature result" and other Get calls seem to work without errors.

Another warning I am getting is my Thermostat is currently set to cool and 78 degrees fahrenheit (25.6 Celsius) and I am getting a warning from HomeBridge about "'Heating Threshold Temperature': characteristic was supplied illegal value: number 25.6 exceeded maximum of 25" from https://developers.homebridge.io/#/characteristic/HeatingThresholdTemperature.

**Logs:**

```
[7/8/2024, 1:06:04 AM] [homebridge-alexa-smarthome] Initialize Devices - UnsupportedDeviceError(Unsupported device: Thermostat with type: THERMOSTAT. Device type is either unsupported or device does not support all the required operations. Device supported operations: setTargetSetpoint,adjustTargetSetpoint,setThermostatMode,setRangeValue,adjustRangeValue,setRangeValue,adjustRangeValue. Currently supported device types are: LIGHT,SWITCH,SMARTLOCK,FAN,SMARTPLUG,THERMOSTAT,ALEXA_VOICE_ENABLED,AIR_QUALITY_MONITOR,VACUUM_CLEANER,GAME_CONSOLE,AIR_FRESHENER.)

[7/8/2024, 1:23:26 AM] [homebridge-alexa-smarthome] Thermostat - Triggered set target state: 2
[7/8/2024, 1:23:39 AM] [homebridge-alexa-smarthome] Thermostat - Triggered set target temperature: 26.1
[7/8/2024, 1:23:39 AM] [homebridge-alexa-smarthome] Alexa-Remote: rate exceeded response ... Retrying once in 32440ms
[7/8/2024, 1:24:12 AM] [homebridge-alexa-smarthome] Thermostat - Set target temperature - RequestUnsuccessful(Error setting smart home device state. Response: {
  "message": "Too many requests. Try again in some time."
})
[7/8/2024, 1:24:12 AM] [homebridge-alexa-smarthome] Thermostat - Service communication error

[7/8/2024, 2:00:05 AM] [homebridge-alexa-smarthome] Querying for changes to Thermostat using query getThermostatStates(
[7/8/2024, 2:00:05 AM] [homebridge-alexa-smarthome] Querying for changes to Thermostat using query getThermostatStates(
[7/8/2024, 2:00:06 AM] [homebridge-alexa-smarthome] Thermostat - Get temperature units result: 1
[7/8/2024, 2:00:06 AM] [homebridge-alexa-smarthome] Querying for changes to Thermostat using query getThermostatStates(
[7/8/2024, 2:00:06 AM] [homebridge-alexa-smarthome] Thermostat - Get current temperature result: 23.3
[7/8/2024, 2:00:06 AM] [homebridge-alexa-smarthome] Querying for changes to Thermostat using query getThermostatStates(
[7/8/2024, 2:00:06 AM] [homebridge-alexa-smarthome] Thermostat - Get target state result: 2
[7/8/2024, 2:00:06 AM] [homebridge-alexa-smarthome] Thermostat - Get target temperature result: 25.6
[7/8/2024, 2:01:05 AM] [homebridge-alexa-smarthome] This plugin generated a warning from the characteristic 'Heating Threshold Temperature': characteristic was supplied illegal value: number 25.6 exceeded maximum of 25. See https://homebridge.io/w/JtMGR for more info.
```

**Plugin Config:**

```json
{
    "devices": [
        "Thermostat"
    ],
    "excludeDevices": [],
    "auth": {
        "refreshInterval": 4,
        "proxy": {
            "clientHost": "localhost",
            "port": 9000
        }
    },
    "amazonDomain": "amazon.com",
    "language": "en-US",
    "performance": {
        "cacheTTL": 60
    },
    "debug": true,
    "_bridge": {
        "username": "XX:XX:XX:XX:XX:XX",
        "port": 53427
    },
    "platform": "HomebridgeAlexaSmartHome"
}
```

**Environment:**

- **Plugin Version**: V2.2.0-alpha.2
- **Homebridge Version**: v1.8.3
- **Node.js Version**: v20.15.0
- **Operating System**: Ubuntu Jammy (22.04.4 LTS)

**Comment by wheeler01** [comment]
I'm having the same problem with my Alexa Thermostat.

**Comment by joeyhage** [comment]
Thanks for the report! I will look into it. Since I don't have a smart thermostat, I had to make some assumptions based on how thermostats worked previously. I will look into it

**Comment by wheeler01** [comment]
Thank you so much. Having to make certain assumptions is understandable. If there is someway I can help or any additional info I can provide, please let me know. I thank you from the bottom of my heart for such a fantastic plug-in. For me it makes everyday life easier.

**Comment by joeyhage** [comment]
I just published v2.2.0-alpha.3. Please let me know if this addresses the issues. Thanks!

**Comment by joeyhage** [comment]
You shouldn't see any more rate limit errors, I realized I had failed to update some of the code for thermostats so it was still using the old way (before version 2.2.0).

**Comment by tateu** [comment]
So far so good.  I've changed the temperature 8-10 times in a row without issue and I've added this in place of Home Assistant Alexa Media Player to control my thermostat in some automations and it has been working correctly for several hours.  Thanks.

**Comment by wheeler01** [comment]
I am not getting the error I was. I am still getting a state error. See below:

[09/07/2024, 13:30:23] [homebridge-alexa-smarthome] Added accessory: Office Thermostat
[09/07/2024, 13:30:23] [homebridge-alexa-smarthome] Office Thermostat - Get power - InvalidResponse(State not available)

If this is nothing to worry about forgive me. But I suspect an invalid state may prevent the device from recording updates.

Thanks for everything.

**Comment by realugbun** [comment]
Confirming that my amazon brand thermostat is working on v2.2.0-alpha.5

**Comment by wheeler01** [comment]
My apologies. I should have confirmed that using v2.2.0-alpha.5 my thermostat does work and for this I am very thankful. The intent of my message was to let you know (for informational purposes only), I do occasionally see the error below:

[09/07/2024, 13:30:23] [homebridge-alexa-smarthome] Added accessory: Office Thermostat
[09/07/2024, 13:30:23] [homebridge-alexa-smarthome] Office Thermostat - Get power - InvalidResponse(State not available)

As for me other than the seemingly harmless errors above, all of my devices that were working before the big change are working again, including my thermostat. Thank you so much for everything.

**Comment by joeyhage** [comment]
@wheeler01 glad to hear it! I appreciate the report because a few other people are reporting similar quirks. I'll investigate a bit but it'll be a few days. I've spent about 30 hours on this the last week and need to step away to get a fresh look.

**Comment by tateu** [comment]
I have the same "Get Power" message too, but only right after a restart/reboot.  If I had to hazard a guess it's because my thermostat does not support the 'turnOn' or 'turnOff' actions from the handlePowerGet function in thermostat-accessory.ts.

```
Thermostat - Get power - InvalidResponse(State not available)
Thermostat - Service communication error
Thermostat - Skipping power-related logic for unsupported devices
```
